// Sync the 2026 World Cup matches from football-data.org into our `matches` model.
//
//   node scripts/sync-matches.mjs --sql > supabase/seed-matches.sql   # generate seed (no DB write)
//   node scripts/sync-matches.mjs                                     # upsert into Supabase (the poller)
//
// Env: FOOTBALL_DATA_TOKEN (required). For upsert mode also SUPABASE_URL + SUPABASE_SERVICE_KEY.
// This is both the one-time seeder and the scheduled updater (results + knockout team progression).
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const DIR = dirname(fileURLToPath(import.meta.url));
const FLAGS = JSON.parse(readFileSync(join(DIR, "flags.json"), "utf8"));

const TOKEN = process.env.FOOTBALL_DATA_TOKEN;
if (!TOKEN) {
  console.error("Missing FOOTBALL_DATA_TOKEN");
  process.exit(1);
}

const STAGE = {
  GROUP_STAGE: "group",
  LAST_32: "r32",
  LAST_16: "r16",
  QUARTER_FINALS: "qf",
  SEMI_FINALS: "sf",
  THIRD_PLACE: "third",
  FINAL: "final",
};
const status = (s) =>
  s === "FINISHED" ? "finished" : s === "IN_PLAY" || s === "PAUSED" ? "live" : "scheduled";
const winner = (w) =>
  w === "HOME_TEAM" ? "HOME" : w === "AWAY_TEAM" ? "AWAY" : w === "DRAW" ? "DRAW" : null;
const side = (t) =>
  t && t.name ? { name: t.name, flag: FLAGS[t.name] ?? null, tla: t.tla ?? null } : { name: null, flag: null, tla: null };

/** Map a football-data.org match to our DB row shape. */
function toRow(m) {
  const home = side(m.homeTeam);
  const away = side(m.awayTeam);
  return {
    id: String(m.id),
    stage: STAGE[m.stage] ?? "group",
    group: m.group ? m.group.replace("GROUP_", "") : null,
    matchday: m.stage === "GROUP_STAGE" ? m.matchday : null,
    kickoff: m.utcDate ?? null,
    home_name: home.name,
    home_flag: home.flag,
    home_tla: home.tla,
    away_name: away.name,
    away_flag: away.flag,
    away_tla: away.tla,
    ft_home: m.score?.fullTime?.home ?? null,
    ft_away: m.score?.fullTime?.away ?? null,
    status: status(m.status),
    duration: m.score?.duration ?? null,
    winner: winner(m.score?.winner),
  };
}

async function fetchMatches() {
  const res = await fetch("https://api.football-data.org/v4/competitions/WC/matches?season=2026", {
    headers: { "X-Auth-Token": TOKEN },
  });
  if (!res.ok) throw new Error(`football-data.org ${res.status}: ${await res.text()}`);
  const { matches } = await res.json();
  return matches.map(toRow);
}

// ── SQL seed mode ────────────────────────────────────────────────────────────
const COLS = [
  "id", "stage", "group", "matchday", "kickoff", "home_name", "home_flag", "home_tla",
  "away_name", "away_flag", "away_tla", "ft_home", "ft_away", "status", "duration", "winner",
];
const sql = (v) =>
  v === null || v === undefined ? "NULL" : typeof v === "number" ? String(v) : `'${String(v).replace(/'/g, "''")}'`;

function toSeedSql(rows) {
  const values = rows
    .map((r) => "  (" + COLS.map((c) => sql(r[c])).join(", ") + ")")
    .join(",\n");
  const cols = COLS.map((c) => `"${c}"`).join(", ");
  const updates = COLS.filter((c) => c !== "id").map((c) => `"${c}" = excluded."${c}"`).join(", ");
  return (
    `-- Generated by scripts/sync-matches.mjs from football-data.org (2026 FIFA World Cup).\n` +
    `-- Idempotent: re-running refreshes every row. Run in the Supabase SQL editor after schema.sql.\n` +
    `insert into public.matches (${cols}) values\n${values}\n` +
    `on conflict (id) do update set ${updates};\n`
  );
}

// ── Upsert mode (the poller) ─────────────────────────────────────────────────
async function upsert(rows) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_KEY;
  if (!url || !key) throw new Error("Upsert mode needs SUPABASE_URL + SUPABASE_SERVICE_KEY");
  const res = await fetch(`${url}/rest/v1/matches?on_conflict=id`, {
    method: "POST",
    headers: {
      apikey: key,
      Authorization: `Bearer ${key}`,
      "Content-Type": "application/json",
      Prefer: "resolution=merge-duplicates,return=minimal",
    },
    body: JSON.stringify(rows),
  });
  if (!res.ok) throw new Error(`Supabase upsert ${res.status}: ${await res.text()}`);
}

const rows = await fetchMatches();
if (process.argv.includes("--sql")) {
  const out = join(DIR, "..", "supabase", "seed-matches.sql");
  writeFileSync(out, toSeedSql(rows), "utf8"); // write directly (clean UTF-8, no BOM)
  console.error(`Wrote ${rows.length} matches to ${out}`);
} else {
  await upsert(rows);
  console.error(`Upserted ${rows.length} matches.`);
}
